### ISSUE TITLE
Edit User Account for SysAdmin module only edits logged in user

### ISSUE THREAD

**Issue by krtjsf** [richard-parayno/carbon-dash#6]
Should be able to pick between users to be able to manage their accounts (credential resets, etc)

**Comment by richard-parayno** [comment]
Added to project backlog. It's just a minor feature which can be fixed in a few hours. Current focus is on the analytics portion.

**Comment by richard-parayno** [comment]
Issue closed. Resolved by passing the selected user id to the edit info page.
